### PR TITLE
Fix #7: Generate manifest.json in output root

### LINKED ISSUE #7: As a developer I would like support for making a Progressive (Evergreen) Web Application
## Type of Change
- [x] New Feature Request
- [ ] Documentation
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
Progressive Web Applications help bridge the web to the mobile world with an emphasis on performance and offline capabilities.  That said, not every application needs to be one.

## Details
Providing support either through code, documentation, or default behavior,  (or all three) would be the goal of this feature request.

I think for now it's ok have the dependencies installed, with documentation for enabling it.  Or maybe a configuration option in **webpack**?

## Tasks
This issue will likely require a few iterations / discussions
1. [x] Add basic manifest 
1. [ ] Enable Service Worker (installed, but off by default?  enforces HTTPS) - see #8

### PR DESCRIPTION
**Pull request by DevLab2425**
## Related Issue

Resolves #7 
## Summary of Changes

I noticed the Webpack Favicon plugin was generating a `manifest.json`, but in a subfolder (`/icons`). By modifying where the icons are generated, the `manifest.json` is generated in the root of the output folder, which is typically a best practice when including a manifest.

With that, a hardcoded `<link />` was added to the HTML to include the `manifest.json` file.

This PR may not complete the PWA task since it does _not_ include a service worker, however, it's a step in the PWA direction.

### CODE REVIEW

**Comment by DevLab2425** [comment]
You're right that a SW is required for the 💯 in Lighthouse, but `manifest.json` gets the benefit of clients using the icons and metadata where possible. The SW does need HTTPS, but it seems the site defaults to that already, no? And with the `manifest.json`, the SW would be the last piece if/when it was prioritized. There's a nice Webpack plugin that includes the SW file into the build and caches the assets when the app loads. 

As far as whether it should be included in CEA, maybe a CLI flag? Could put the pieces in place for something basic, with a set of dedicated instructions on how and where to make changes?

**Comment by thescientist13** [comment]
Cool, so sounds like we would technically want to keep #8 open and add these takeaways / additional actions items and keep it open after merging this.  I'll make the updates in the issue.

> but it seems the site defaults to that already, no?

not sure what you mean here?

**Comment by DevLab2425** [comment]
> but it seems the site defaults to ~that~ HTTPS already, no?

**Comment by thescientist13** [comment]
@DevLab2425 
a good point about #7 and #8.  This seems unobtrusive enough so let's get it in and do the rest of the work in #8.

> but it seems the site defaults to ~~that~~ HTTPS already, no?

hah, yes, I knew you mean HTTPS, I was more inquiring about your assumption of default behavior.  To my knowledge, this project doesn't yet make any assumptions about that, but by enabling a SW by default, it would.

**Pull request merged**
