### PR TITLE
Adding Missing Manifest, closes #66

### LINKED ISSUE #66: Missing Manifest
## Type of Change
- [ ] New Feature Request
- [ ] Documentation
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary
Generated asset manifest is missing.

## Details

> Manifest: Line: 1, column: 1, Unexpected token.

## Solution

Add webpack manifest plugin to webpack config

### PR DESCRIPTION
**Pull request by hutchgrant**
## Related Issue
closes #66 

## Summary of Changes
1. Added Webpack Manifest Plugin
2. added new plugin to webpack common config
3. Added Public Path
4. Set icon file path to icon folder
5. Set js file path to js folder

### CODE REVIEW

**Comment by hutchgrant** [comment]
The public path wasn't set which caused problems when using a router.

The icon manifest was conflicting with the app manifest. Both app and icon manifests now work. The icons and js files are now in their respective directories.

**Comment by hutchgrant** [comment]
So I've taken another look at it now and it's actually three related issues which you probably prefer to differentiate into three github issues but they're all kind of related(webpack config issues). 

### Problems

1) missing manifest in development environment. The manifest and favicons are only built until production, therefore we get the missing manifest error.

2) the output publicPath isn't currently set, which is a problem if you expect the app to be doing routing.

3) the icons are all being put into the public directory and not the icons sub directory. This is clearly not the intention, as we are generating a separate folder specifically for icons.

### Solutions

1. use webpack-manifest-plugin in the webpack.config.develop to generate a manifest (doesn't generate favicons ofc) but other than resolve the error it's not really useful for our case. It's just generating a list of assets we already know the path to. I didn't test this properly the first time.

2. Add publicPath constant to webpack.common.js I suppose this could be a separate issue if you'd like. It's only a single line fix.

3.  If I adjust the prefix path of the FaviconsWebpackPlugin to the icons folder, the generated manifest directory will change with it. So we would also have to alter the index.html for the manifest to:

```
<link rel="manifest" href="/icons/manifest.json" />
```
If you don't have any problems with that, then these resolve the issues.

**Comment by thescientist13** [comment]
@hutchgrant 
Sounds good to me, let's give it a try!  (I think I'm ok with it not working in development mode, but I think I was testing using `yarn serve`, fwiw)

**Comment by hutchgrant** [comment]
I just noticed this basically reverses #20 while I agree, I'd prefer the manifest.json on root, the problem is when the prefix was modified all the icons also went into root, which is not ideal.

**Comment by thescientist13** [comment]
closing in favor of #77

**Pull request closed without merging**
